version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini_marketplace
      MYSQL_USER: marketplace
      MYSQL_PASSWORD: marketplace
    command: ["--default-authentication-plugin=mysql_native_password", "--skip-host-cache", "--skip-name-resolve"]
    volumes:
      - db_data:/var/lib/mysql
    # NO port mapping to avoid conflicts; backend connects via service name
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    # No host port published to avoid conflicts
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    # No host port published to avoid conflicts; backend uses service name:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=marketplace
      - DB_PASSWORD=marketplace
      - DB_NAME=mini_marketplace
      - REDIS_URL=redis://redis:6379
      - ES_NODE=http://elasticsearch:9200
      - JWT_SECRET=supersecret
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:4000
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  db_data:
  es_data: